// Shared session-scoped cookie jar used by both proxy.ts and site-proxy.ts.
// Key: sessionId (generated by the client, one per preview tab)
//   → domain → cookie-name → cookie-value

type SessionEntry = { cookies: Map<string, Map<string, string>>; ts: number };
const sessions = new Map<string, SessionEntry>();
const SESSION_TTL_MS = 60 * 60 * 1000; // 1 hour

setInterval(() => {
  const cutoff = Date.now() - SESSION_TTL_MS;
  for (const [id, s] of sessions) {
    if (s.ts < cutoff) sessions.delete(id);
  }
}, SESSION_TTL_MS);

function getOrCreate(sid: string): SessionEntry {
  let s = sessions.get(sid);
  if (!s) { s = { cookies: new Map(), ts: Date.now() }; sessions.set(sid, s); }
  else s.ts = Date.now();
  return s;
}

export function readCookies(sid: string, domain: string): string {
  const s = sessions.get(sid);
  if (!s) return "";
  s.ts = Date.now();
  const dc = s.cookies.get(domain);
  if (!dc || dc.size === 0) return "";
  return [...dc.entries()].map(([k, v]) => `${k}=${v}`).join("; ");
}

export function storeCookies(sid: string, domain: string, setCookieHeaders: string[]): void {
  const s = getOrCreate(sid);
  let dc = s.cookies.get(domain);
  if (!dc) { dc = new Map(); s.cookies.set(domain, dc); }
  for (const hdr of setCookieHeaders) {
    const [nv] = hdr.split(";");
    const eq = nv.indexOf("=");
    if (eq < 0) continue;
    dc.set(nv.slice(0, eq).trim(), nv.slice(eq + 1).trim());
  }
}

export function isPrivateHostname(hostname: string): boolean {
  if (!hostname) return true;
  const h = hostname.toLowerCase().replace(/^\[|\]$/g, ""); // strip IPv6 brackets
  if (h === "localhost" || h.endsWith(".localhost") || h.endsWith(".internal") || h.endsWith(".local")) return true;
  if (/^127\./.test(h)) return true;                         // loopback
  if (/^10\./.test(h)) return true;                          // private A
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(h)) return true;     // private B
  if (/^192\.168\./.test(h)) return true;                    // private C
  if (/^169\.254\./.test(h)) return true;                    // link-local + CLOUD METADATA (169.254.169.254)
  if (/^100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\./.test(h)) return true; // carrier-grade NAT 100.64/10
  if (/^0\./.test(h)) return true;                           // 0.0.0.0/8 (incl. 0.0.0.0)
  if (h === "::1" || h === "::") return true;                // IPv6 loopback / unspecified
  if (/^fe80:/i.test(h)) return true;                        // IPv6 link-local
  if (/^f[cd][0-9a-f]{2}:/i.test(h)) return true;            // IPv6 unique-local fc00::/7
  if (/^::ffff:/i.test(h)) {                                 // IPv4-mapped IPv6 → range-check the embedded v4
    const v4 = h.replace(/^::ffff:/i, "");
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(v4)) return isPrivateHostname(v4);
  }
  return false;
}
