// Shared session-scoped cookie jar used by both proxy.ts and site-proxy.ts.
// Key: sessionId (generated by the client, one per preview tab)
//   → domain → cookie-name → cookie-value

type SessionEntry = { cookies: Map<string, Map<string, string>>; ts: number };
const sessions = new Map<string, SessionEntry>();
const SESSION_TTL_MS = 60 * 60 * 1000; // 1 hour

setInterval(() => {
  const cutoff = Date.now() - SESSION_TTL_MS;
  for (const [id, s] of sessions) {
    if (s.ts < cutoff) sessions.delete(id);
  }
}, SESSION_TTL_MS);

function getOrCreate(sid: string): SessionEntry {
  let s = sessions.get(sid);
  if (!s) { s = { cookies: new Map(), ts: Date.now() }; sessions.set(sid, s); }
  else s.ts = Date.now();
  return s;
}

export function readCookies(sid: string, domain: string): string {
  const s = sessions.get(sid);
  if (!s) return "";
  s.ts = Date.now();
  const dc = s.cookies.get(domain);
  if (!dc || dc.size === 0) return "";
  return [...dc.entries()].map(([k, v]) => `${k}=${v}`).join("; ");
}

export function storeCookies(sid: string, domain: string, setCookieHeaders: string[]): void {
  const s = getOrCreate(sid);
  let dc = s.cookies.get(domain);
  if (!dc) { dc = new Map(); s.cookies.set(domain, dc); }
  for (const hdr of setCookieHeaders) {
    const [nv] = hdr.split(";");
    const eq = nv.indexOf("=");
    if (eq < 0) continue;
    dc.set(nv.slice(0, eq).trim(), nv.slice(eq + 1).trim());
  }
}

export function isPrivateHostname(hostname: string): boolean {
  if (!hostname || hostname === "localhost") return true;
  if (/^127\./.test(hostname)) return true;
  if (/^10\./.test(hostname)) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(hostname)) return true;
  if (/^192\.168\./.test(hostname)) return true;
  if (hostname === "::1" || hostname === "0.0.0.0") return true;
  return false;
}
